if vim.g.neovide then
	vim.g.neovide_cursor_animate_command_line = false
	vim.g.neovide_cursor_animate_in_insert_mode = false
	vim.g.neovide_cursor_animation_length = 0
	vim.g.neovide_cursor_antialiasing = false
	vim.g.neovide_cursor_trail_size = 0
	vim.g.neovide_no_idle = true
	vim.g.neovide_no_vsync = true
	vim.g.neovide_opacity = 0.7
	vim.g.neovide_padding_bottom = 0
	vim.g.neovide_padding_left = 0
	vim.g.neovide_padding_right = 0
	vim.g.neovide_padding_top = 0
	vim.g.neovide_refresh_rate = 144
	vim.g.neovide_refresh_rate_idle = 0
	vim.g.neovide_remember_window_size = true
	vim.g.neovide_scroll_animation_length = 0
	vim.o.guifont = "Myna:h11"
	vim.opt.guicursor = "i-v:hor20-Cursor/lCursor"
end
