return {
	"tjdevries/colorbuddy.nvim",
	"Verf/deepwhite.nvim",
	"lifepillar/vim-gruvbox8",
	"mrjones2014/lighthaus.nvim",
	"phanviet/vim-monokai-pro",
	"mhartington/oceanic-next",
	"fenetikm/falcon",
	"katawful/kat.nvim",
	-- "rebelot/kanagawa.nvim", -- has own config in ./kanagawa.lua
	"zootedb0t/citruszest.nvim",
	"EdenEast/nightfox.nvim",
	"shaeinst/roshnivim-cs",
	"npxbr/gruvbox.nvim",
	"eddyekofo94/gruvbox-flat.nvim",
	"rktjmp/lush.nvim",
	"savq/melange",
	"ishan9299/modus-theme-vim",
	"ishan9299/nvim-solarized-lua",
	"aktersnurra/no-clown-fiesta.nvim",
	"nyoom-engineering/oxocarbon.nvim",
	{ "catppuccin/nvim", name = "catppuccin", priority = 1000 },
	{ "projekt0n/github-nvim-theme", priority = 1000 },
	"jhchabran/monarized",
}
